# Generated by Django 4.1.7 on 2023-04-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('Description', models.TextField(max_length=1000)),
                ('Image', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
