# Generated by Django 4.1.7 on 2023-04-03 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='Image',
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='logo_footer.png', upload_to='images'),
        ),
    ]
