# Generated by Django 4.1.7 on 2023-04-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_description_menuitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='link',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
