# Generated by Django 4.1.7 on 2023-04-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='logo_footer.png', upload_to='restaurant\\static\\img\\menu_items'),
        ),
    ]
